volumes:
  static:
  media:
  postgres_data:

networks:
  backend:
    driver: bridge

services:
  postgres:
    image: postgres:16-alpine
    container_name: shared_postgres
    environment:
      POSTGRES_DB: offersAdmin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5158
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped


  litestar:
    build:
      context: ./lifestar
      dockerfile: Dockerfile
    container_name: litestar
    env_file:
      - ./lifestar/app/.env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
    - "5000:5000"
    networks:
      - backend
    restart: unless-stopped

  nginx:
    build: ./nginx/conf
    container_name: nginx
    volumes:
      - ./static:/opt/static
      - ./media:/opt/media
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/ssl/default:/etc/ssl/default
      - ./nginx/ssl/.well-known:/opt/offersAdmin/.well-known
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - litestar
    networks:
      - backend
    restart: unless-stopped