upstream django {
    server admin_panel:8000;
}

upstream litestar {
    server litestar:5000;
}

# HTTP server for all domains (port 80) - Redirect to HTTPS
server {
    listen 80;
    server_name domain.com www.domain.com;
    server_tokens off;

    location /.well-known/acme-challenge {
        alias /opt/offersAdmin/.well-known/acme-challenge;
    }

    location /static/ {
        alias /opt/static/;
    }

    location /media/ {
        alias /opt/media/;
    }

    location /api/ {
        proxy_set_header X-Forwarded-Proto http;
        proxy_set_header X-Url-Scheme $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_pass http://litestar;
    }

    location /schema {
        proxy_set_header X-Forwarded-Proto http;
        proxy_set_header X-Url-Scheme $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_pass http://litestar;
    }

    location / {
        proxy_set_header X-Forwarded-Proto http;
        proxy_set_header X-Url-Scheme $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_pass http://django;
    }
}

# # HTTPS server for all domains (port 443)
# server {
#     listen 443 ssl;
#     server_name domain.com www.domain.com;
#     server_tokens off;
#     ssl_certificate /etc/ssl/default/fullchain.pem;
#     ssl_certificate_key /etc/ssl/default/privkey.pem;

#     location /static/ {
#         alias /opt/static/;
#     }

#     location /media/ {
#         alias /opt/media/;
#     }

#     location /api/ {
#         proxy_set_header X-Forwarded-Proto https;
#         proxy_set_header X-Url-Scheme $scheme;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header Host $http_host;
#         proxy_redirect off;
#         proxy_pass http://litestar;
#     }

#     location /schema {
#         proxy_set_header X-Forwarded-Proto https;
#         proxy_set_header X-Url-Scheme $scheme;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header Host $http_host;
#         proxy_redirect off;
#         proxy_pass http://litestar;
#     }

#     location / {
#         proxy_set_header X-Forwarded-Proto https;
#         proxy_set_header X-Url-Scheme $scheme;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header Host $http_host;
#         proxy_redirect off;
#         proxy_pass http://django;
#     }
# }